## Preparing for loading

In [284]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

In [285]:
from IPython.display import display, HTML

# Desativa o wrapping
display(HTML("<style>td { white-space: nowrap; }</style>"))

In [286]:
# Load the dataset
path = os.path.join('..', 'src', 'Data', 'raw', 'COVID clinical trials.csv')
df = pd.read_csv(path)

df.head()

,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Other IDs,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,COVID-IDNow,"Active, not recruiting",No Results Available,Covid19,Diagnostic Test: ID Now™ COVID-19 Screening Test,Evaluate the diagnostic performance of the ID ...,Groupe Hospitalier Paris Saint Joseph,...,COVID-IDNow,"November 9, 2020","December 22, 2020","April 30, 2021","March 8, 2021",NaN,"March 8, 2021","Groupe Hospitalier Paris Saint-Joseph, Paris, ...",NaN,https://ClinicalTrials.gov/show/NCT04785898
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,COVID-19,Not yet recruiting,No Results Available,SARS-CoV-2 Infection,Drug: Drug COVID19-0001-USR|Drug: normal saline,Change on viral load results from baseline aft...,United Medical Specialties,...,COVID19-0001-USR,"November 2, 2020","December 15, 2020","January 29, 2021","October 20, 2020",NaN,"October 20, 2020","Cimedical, Barranquilla, Atlantico, Colombia",NaN,https://ClinicalTrials.gov/show/NCT04595136
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,TAC-COVID19,Recruiting,No Results Available,covid19,Other: Lung CT scan analysis in COVID-19 patients,A qualitative analysis of parenchymal lung dam...,University of Milano Bicocca,...,TAC-COVID19,"May 7, 2020","June 15, 2021","June 15, 2021","May 20, 2020",NaN,"November 9, 2020","Ospedale Papa Giovanni XXIII, Bergamo, Italy|P...",NaN,https://ClinicalTrials.gov/show/NCT04395482
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,COVID-19,"Active, not recruiting",No Results Available,COVID,Diagnostic Test: COVID 19 Diagnostic Test,Proportion of asymptomatic subjects|Proportion...,Hong Kong Sanatorium & Hospital,...,RC-2020-08,"May 25, 2020","July 31, 2020","August 31, 2020","June 4, 2020",NaN,"June 4, 2020","Hong Kong Sanatorium & Hospital, Hong Kong, Ho...",NaN,https://ClinicalTrials.gov/show/NCT04416061
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,TMF-COVID-19,Recruiting,No Results Available,Maternal Fetal Infection Transmission|COVID-19...,Diagnostic Test: Diagnosis of SARS-Cov2 by RT-...,COVID-19 by positive PCR in cord blood and / o...,Centre Hospitalier Régional d'Orléans|Centre d...,...,CHRO-2020-10,"May 5, 2020",May 2021,May 2021,"May 20, 2020",NaN,"June 4, 2020","CHR Orléans, Orléans, France",NaN,https://ClinicalTrials.gov/show/NCT04395924

In [287]:
df.columns

Index(['Rank', 'NCT Number', 'Title', 'Acronym', 'Status', 'Study Results',
       'Conditions', 'Interventions', 'Outcome Measures',
       'Sponsor/Collaborators', 'Gender', 'Age', 'Phases', 'Enrollment',
       'Funded Bys', 'Study Type', 'Study Designs', 'Other IDs', 'Start Date',
       'Primary Completion Date', 'Completion Date', 'First Posted',
       'Results First Posted', 'Last Update Posted', 'Locations',
       'Study Documents', 'URL'],
      dtype='str')

In [288]:
# Selecting columns for the studies table
cols_studies = ['Rank','NCT Number', 'Title', 'Status', 'Acronym', 'Phases', 
    'Study Type', 'Start Date', 'Completion Date', 'Primary Completion Date', 'Enrollment', 'Age', 'Gender', 'First Posted', 'Last Update Posted'
]

# Creating the dataframe for studies
df_studies = df[cols_studies].copy()

In [289]:
# Checking Date Formats
df_studies[['Start Date', 'Completion Date', 'Primary Completion Date', 'First Posted', 'Last Update Posted']].head()

,Start Date,Completion Date,Primary Completion Date,First Posted,Last Update Posted
0,"November 9, 2020","April 30, 2021","December 22, 2020","March 8, 2021","March 8, 2021"
1,"November 2, 2020","January 29, 2021","December 15, 2020","October 20, 2020","October 20, 2020"
2,"May 7, 2020","June 15, 2021","June 15, 2021","May 20, 2020","November 9, 2020"
3,"May 25, 2020","August 31, 2020","July 31, 2020","June 4, 2020","June 4, 2020"
4,"May 5, 2020",May 2021,May 2021,"May 20, 2020","June 4, 2020"

In [290]:
#Converting date columns to datetime
# Columns that in SQL are TIMESTAMP 
timestamp_cols = ['First Posted', 'Last Update Posted']

# Columns that in SQL are DATE
date_cols = ['Start Date', 'Completion Date', 'Primary Completion Date']

# Converting all date columns to datetime
for col in (timestamp_cols + date_cols):
    df_studies[col] = pd.to_datetime(df_studies[col], errors='coerce')

# Defining the date format for TIMESTAMP and DATE columns
for col in timestamp_cols:
    df_studies[col] = df_studies[col].dt.strftime('%Y-%m-%d %H:%M:%S')

for col in date_cols:
    df_studies[col] = df_studies[col].dt.strftime('%Y-%m-%d')

C:\Users\User\AppData\Local\Temp\ipykernel_17792\1177570128.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_studies[col] = pd.to_datetime(df_studies[col], errors='coerce')
C:\Users\User\AppData\Local\Temp\ipykernel_17792\1177570128.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_studies[col] = pd.to_datetime(df_studies[col], errors='coerce')
C:\Users\User\AppData\Local\Temp\ipykernel_17792\1177570128.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_studies[col] = pd.to_datetime(df_studies[col], errors='coerce')
C:\Users\User\AppData\Local\Temp\ipykernel_17792\1177570128.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_studies[col] = pd.to_datetime(df_studies[col], errors='coerce')
C:\Users\User\AppData\Local\Temp\ipykernel_17792\1177570128.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_studies[col] = pd.to_datetime(df_studies[col], errors='coerce')

In [291]:
df_studies.head()

,Rank,NCT Number,Title,Status,Acronym,Phases,Study Type,Start Date,Completion Date,Primary Completion Date,Enrollment,Age,Gender,First Posted,Last Update Posted
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,"Active, not recruiting",COVID-IDNow,Not Applicable,Interventional,2020-11-09,2021-04-30,2020-12-22,1000.0,"18 Years and older (Adult, Older Adult)",All,2021-03-08 00:00:00,2021-03-08 00:00:00
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,Not yet recruiting,COVID-19,Phase 1|Phase 2,Interventional,2020-11-02,2021-01-29,2020-12-15,60.0,"18 Years and older (Adult, Older Adult)",All,2020-10-20 00:00:00,2020-10-20 00:00:00
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,Recruiting,TAC-COVID19,NaN,Observational,2020-05-07,2021-06-15,2021-06-15,500.0,"18 Years and older (Adult, Older Adult)",All,2020-05-20 00:00:00,2020-11-09 00:00:00
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,"Active, not recruiting",COVID-19,NaN,Observational,2020-05-25,2020-08-31,2020-07-31,2500.0,"Child, Adult, Older Adult",All,2020-06-04 00:00:00,2020-06-04 00:00:00
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,Recruiting,TMF-COVID-19,NaN,Observational,2020-05-05,2021-05-01,2021-05-01,50.0,18 Years to 48 Years (Adult),Female,2020-05-20 00:00:00,2020-06-04 00:00:00

In [292]:
# Checking for missing values in date columns
df_studies[['Start Date', 'Completion Date', 'Primary Completion Date', 'First Posted', 'Last Update Posted']].isna().sum()

Start Date                 34
Completion Date            36
Primary Completion Date    36
First Posted                0
Last Update Posted          0
dtype: int64

In [293]:
# isolating rows with missing dates
missing_dates = df_studies[df_studies['Start Date'].isna() | df_studies['Completion Date'].isna() | df_studies['Primary Completion Date'].isna()]

# Filling missing date values with empty 1900-01-01 for MySQL compatibility
df_studies['Start Date'] = df_studies['Start Date'].fillna('1900-01-01')
df_studies['Completion Date'] = df_studies['Completion Date'].fillna('1900-01-01')
df_studies['Primary Completion Date'] = df_studies['Primary Completion Date'].fillna('1900-01-01')

In [294]:
# Re-checking for missing values in date columns
df_studies[['Start Date', 'Completion Date', 'Primary Completion Date', 'First Posted', 'Last Update Posted']].isna().sum()

Start Date                 0
Completion Date            0
Primary Completion Date    0
First Posted               0
Last Update Posted         0
dtype: int64

In [295]:
df_studies[['NCT Number', 'Age']]

       NCT Number                                           Age
0     NCT04785898     18 Years and older   (Adult, Older Adult)
1     NCT04595136     18 Years and older   (Adult, Older Adult)
2     NCT04395482     18 Years and older   (Adult, Older Adult)
3     NCT04416061                     Child, Adult, Older Adult
4     NCT04395924                18 Years to 48 Years   (Adult)
...           ...                                           ...
5778  NCT04011644  21 Years to 100 Years   (Adult, Older Adult)
5779  NCT04681339         3 Months to 18 Years   (Child, Adult)
5780  NCT04740229                18 Years to 64 Years   (Adult)
5781  NCT04804917          8 Years to 20 Years   (Child, Adult)
5782  NCT04680000     18 Years and older   (Adult, Older Adult)

[5783 rows x 2 columns]

In [296]:
# Function to extract minimum and maximum age from the 'Age' column
def extract_age_range(age_str):
    '''Extracts minimum and maximum age from a given age string.'''

    if pd.isna(age_str):
        return None, None
    
    age_str = str(age_str).lower()
    
    # Normalizing time units to years
    def to_years(val, unit):
        '''Converts a value with a given time unit to years.'''
        val = float(val)
        if 'month' in unit: return round(val / 12, 2)
        if 'week' in unit: return round(val / 52, 2)
        if 'day' in unit: return round(val / 365, 2)
        return val

    # Extracting all age values and their corresponding units
    matches = re.findall(r'(\d+)\s+(year|month|week|day)', age_str)
    
    min_age, max_age = None, None
    
    if matches:
        years_list = [to_years(val, unit) for val, unit in matches]
        
        if "and older" in age_str:
            min_age = years_list[0]
            max_age = 120.0 # to represent "and older"
        elif "up to" in age_str:
            min_age = 0.0
            max_age = years_list[0]
        elif "to" in age_str and len(years_list) >= 2:
            min_age = years_list[0]
            max_age = years_list[1]
        elif len(years_list) == 1:
            min_age = years_list[0]
            max_age = None
    else:
        # for cases where age is described in terms of categories (e.g., "child", "adult", "older adult")
        if "child" in age_str:
            min_age = 0
            if "older adult" in age_str: max_age = 120
            elif "adult" in age_str: max_age = 64
            else: max_age = 17
        elif "older adult" in age_str:
            min_age = 65
            max_age = 120
        elif "adult" in age_str:
            min_age = 18
            max_age = 64
            
    return min_age, max_age

# Aplying the function to extract minimum and maximum age and creating new columns
df_studies[['minimum_age', 'maximum_age']] = df_studies['Age'].apply(lambda x: pd.Series(extract_age_range(x)))

In [297]:
# Verification of the result
df_studies[['Age', 'minimum_age', 'maximum_age']].head(10)

                                                Age  minimum_age  maximum_age
0         18 Years and older   (Adult, Older Adult)         18.0        120.0
1         18 Years and older   (Adult, Older Adult)         18.0        120.0
2         18 Years and older   (Adult, Older Adult)         18.0        120.0
3                         Child, Adult, Older Adult          0.0        120.0
4                    18 Years to 48 Years   (Adult)         18.0         48.0
5       18 Years to 75 Years   (Adult, Older Adult)         18.0         75.0
6                    18 Years to 45 Years   (Adult)         18.0         45.0
7       18 Years to 99 Years   (Adult, Older Adult)         18.0         99.0
8                    18 Years to 55 Years   (Adult)         18.0         55.0
9  15 Years and older   (Child, Adult, Older Adult)         15.0        120.0

In [298]:
# Renaming columns to match the database schema
df_studies = df_studies.rename(columns={
    'Rank':'study_id',
    'NCT Number': 'nct_id',
    'Title': 'title',
    'Status': 'status',
    'Acronym': 'acronym',
    'Phases': 'phase',
    'Study Type': 'study_type',
    'Start Date': 'start_date',
    'Completion Date': 'completion_date',
    'Primary Completion Date': 'primary_completion_date',
    'Enrollment': 'enrollment',
    'Gender': 'gender',
    'First Posted': 'created_at',
    'Last Update Posted': 'updated_at'
})

# dropping the original 'Age' column as we now have 'minimum_age' and 'maximum_age'
df_studies = df_studies.drop(columns=['Age'], errors='ignore')

#Checking the final structure of the dataframe
df_studies.head()

,study_id,nct_id,title,status,acronym,phase,study_type,start_date,completion_date,primary_completion_date,enrollment,gender,created_at,updated_at,minimum_age,maximum_age
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,"Active, not recruiting",COVID-IDNow,Not Applicable,Interventional,2020-11-09,2021-04-30,2020-12-22,1000.0,All,2021-03-08 00:00:00,2021-03-08 00:00:00,18.0,120.0
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,Not yet recruiting,COVID-19,Phase 1|Phase 2,Interventional,2020-11-02,2021-01-29,2020-12-15,60.0,All,2020-10-20 00:00:00,2020-10-20 00:00:00,18.0,120.0
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,Recruiting,TAC-COVID19,NaN,Observational,2020-05-07,2021-06-15,2021-06-15,500.0,All,2020-05-20 00:00:00,2020-11-09 00:00:00,18.0,120.0
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,"Active, not recruiting",COVID-19,NaN,Observational,2020-05-25,2020-08-31,2020-07-31,2500.0,All,2020-06-04 00:00:00,2020-06-04 00:00:00,0.0,120.0
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,Recruiting,TMF-COVID-19,NaN,Observational,2020-05-05,2021-05-01,2021-05-01,50.0,Female,2020-05-20 00:00:00,2020-06-04 00:00:00,18.0,48.0

In [299]:
# Final check of the dataframe structure and data types
df_studies.info()

<class 'pandas.DataFrame'>
RangeIndex: 5783 entries, 0 to 5782
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   study_id                 5783 non-null   int64
 1   nct_id                   5783 non-null   str
 2   title                    5783 non-null   str
 3   status                   5783 non-null   str
 4   acronym                  2480 non-null   str
 5   phase                    3322 non-null   str
 6   study_type               5783 non-null   str
 7   start_date               5783 non-null   str
 8   completion_date          5783 non-null   str
 9   primary_completion_date  5783 non-null   str
 10  enrollment               5749 non-null   float64
 11  gender                   5773 non-null   str
 12  created_at               5783 non-null   str
 13  updated_at               5783 non-null   str
 14  minimum_age              5783 non-null   float64
 15  maximum_age              5783 non-null   float64
dtypes: float64(3), int64(1), str(12)
memory usage: 723.0 KB

In [300]:
# Converting enrollment to integer type

df_studies['enrollment'] = df_studies['enrollment'].astype('Int64')

In [301]:
# Checking missing enrollment values
df_studies['enrollment'].isna().sum()

np.int64(34)

In [302]:
# Filling missing enrollment values with -1 for MySQL compatibility
df_studies['enrollment'] = df_studies['enrollment'].fillna(-1)

In [303]:
# Re-checking the dataframe
df_studies.info()

<class 'pandas.DataFrame'>
RangeIndex: 5783 entries, 0 to 5782
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   study_id                 5783 non-null   int64
 1   nct_id                   5783 non-null   str
 2   title                    5783 non-null   str
 3   status                   5783 non-null   str
 4   acronym                  2480 non-null   str
 5   phase                    3322 non-null   str
 6   study_type               5783 non-null   str
 7   start_date               5783 non-null   str
 8   completion_date          5783 non-null   str
 9   primary_completion_date  5783 non-null   str
 10  enrollment               5783 non-null   Int64
 11  gender                   5773 non-null   str
 12  created_at               5783 non-null   str
 13  updated_at               5783 non-null   str
 14  minimum_age              5783 non-null   float64
 15  maximum_age              5783 non-null   float64
dtypes: Int64(1), float64(2), int64(1), str(12)
memory usage: 728.7 KB

In [304]:
# Isolating Expanded Access studies
df_expanded_access = df_studies[df_studies['study_type'] == 'Expanded Access'].copy()
df_expanded_access.head()

,study_id,nct_id,title,status,acronym,phase,study_type,start_date,completion_date,primary_completion_date,enrollment,gender,created_at,updated_at,minimum_age,maximum_age
3547,3548,NCT04476706,Canakinumab MAP in COVID-19 Pneumonia With CRS,No longer available,NaN,NaN,Expanded Access,1900-01-01,1900-01-01,1900-01-01,-1,All,2020-07-20 00:00:00,2021-02-03 00:00:00,18.0,100.0

In [305]:
# Creating the 'enrollment_type' column based on the 'status' of the study
df_studies['enrollment_type'] = np.where(
    df_studies['status'] == 'Completed', 
    'Actual', 
    'Estimated'
)

# Original dataset does not have 'brief_summary' and 'eligibility_criteria' columns
# They will be created as placeholders
df_studies['brief_summary'] = 'Not Specified'
df_studies['eligibility_criteria'] = 'Not Specified'

# Verifying the final result
df_studies.head()

,study_id,nct_id,title,status,acronym,phase,study_type,start_date,completion_date,primary_completion_date,enrollment,gender,created_at,updated_at,minimum_age,maximum_age,enrollment_type,brief_summary,eligibility_criteria
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,"Active, not recruiting",COVID-IDNow,Not Applicable,Interventional,2020-11-09,2021-04-30,2020-12-22,1000,All,2021-03-08 00:00:00,2021-03-08 00:00:00,18.0,120.0,Estimated,Not Specified,Not Specified
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,Not yet recruiting,COVID-19,Phase 1|Phase 2,Interventional,2020-11-02,2021-01-29,2020-12-15,60,All,2020-10-20 00:00:00,2020-10-20 00:00:00,18.0,120.0,Estimated,Not Specified,Not Specified
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,Recruiting,TAC-COVID19,NaN,Observational,2020-05-07,2021-06-15,2021-06-15,500,All,2020-05-20 00:00:00,2020-11-09 00:00:00,18.0,120.0,Estimated,Not Specified,Not Specified
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,"Active, not recruiting",COVID-19,NaN,Observational,2020-05-25,2020-08-31,2020-07-31,2500,All,2020-06-04 00:00:00,2020-06-04 00:00:00,0.0,120.0,Estimated,Not Specified,Not Specified
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,Recruiting,TMF-COVID-19,NaN,Observational,2020-05-05,2021-05-01,2021-05-01,50,Female,2020-05-20 00:00:00,2020-06-04 00:00:00,18.0,48.0,Estimated,Not Specified,Not Specified

In [306]:
# Exporting
export_path = os.path.join('..', 'src', 'data', 'processed', 'structured tables')

df_studies.to_csv(os.path.join(export_path, 'studies_tb.csv'), index=False, na_rep='')

 ---

In [ ]:
# Selection of columns for the locations table
df_locations = df[['Rank','Locations']].copy()

# Addressing the issue of multiple locations in a single string by splitting them into lists
df_locations['Locations'] = df_locations['Locations'].str.split('|')

# Exploding the 'Locations' column to create a new row for each location
df_locations = df_locations.explode('Locations')

In [ ]:
# Function to split location details into separate columns
def split_location_details(loc_str):
    if pd.isna(loc_str) or loc_str == '':
        return None, None, None, None
    
    # Cleaning whitespaces and splitting the location string by commas
    parts = [p.strip() for p in str(loc_str).split(',')]
    n = len(parts)
    
    facility, city, state, country = None, None, None, None
    
    if n >= 2:
        # Country always appears last
        country = parts[-1]
        
        # Defining a list of countries that typically include state information in the location string
        countries_with_states = ['united states', 'usa', 'us', 'canada', 'brazil', 'australia', 'mexico', 'colombia']
        
        if country.lower() in countries_with_states and n >= 3:
            # Logic for countries with states
            state = parts[-2]
            city = parts[-3]
            # All that remains on the left is the Facility
            facility = ", ".join(parts[:-3]) if n > 3 else None
        else:
            # Logic for Europe/Rest of the World
            city = parts[-2]
            # All that remains on the left is the Facility
            facility = ", ".join(parts[:-2]) if n > 2 else None
            state = None 

    # If the facility is empty, the first is the city
    if not facility and n == 2:
        city, country = parts[0], parts[1]
        
    return facility, city, state, country

# Applying the function to split location details into separate columns
df_locations[['facility', 'city', 'state', 'country']] = df_locations['Locations'].apply(
    lambda x: pd.Series(split_location_details(x))
)

In [ ]:
# dropping the original 'Locations' 
df_locations = df_locations.drop(columns='Locations', errors='ignore')

df_locations.head(10)

,Rank,facility,city,state,country
0,1,"Groupe Hospitalier Paris Saint-Joseph, Paris",Ile De France,NaN,France
1,2,Cimedical,Barranquilla,Atlantico,Colombia
2,3,Ospedale Papa Giovanni XXIII,Bergamo,NaN,Italy
2,3,Policlinico San Marco-San Donato group,Bergamo,NaN,Italy
2,3,Azienda Ospedaliero-Universitaria di Ferrara,Ferrara,NaN,Italy
2,3,ASST di Lecco Ospedale Alessandro Manzoni,Lecco,NaN,Italy
2,3,"ASST Melegnano-Martesana, Ospedale Santa Maria...",Melzo,NaN,Italy
2,3,ASST Monza,Monza,NaN,Italy
2,3,AUSL Romagna-Ospedale Infermi di Rimini,Rimini,NaN,Italy
2,3,Istituto per la Sicurezza Sociale-Ospedale del...,San Marino,NaN,San Marino

In [ ]:
# Renaming columns to match the database schema
df_locations = df_locations.rename(columns={
    'Rank':'study_id',
})

In [ ]:
# Exporting 
df_locations.to_csv(os.path.join(export_path, 'locations_tb.csv'), index=False)

 ---

In [ ]:
# Selecting columns for the interventions table
df_interv = df[['Rank', 'Interventions']].copy()

# Renaming columns to match the database schema
df_interv = df_interv.rename(columns={
    'Rank':'study_id'
})

# Exploding the 'Interventions' column to create a new row for each intervention
df_interv['Interventions'] = df_interv['Interventions'].str.split('|')
df_interv = df_interv.explode('Interventions')

# Checking for missing values in date columns
df_interv[['Interventions']].isna().sum()

Interventions    886
dtype: int64

In [ ]:
# Removing empty rows
df_interv = df_interv.dropna(subset=['Interventions'])

# Dividing the 'Interventions' column into 'type' and 'name'
df_interv[['intervention_type', 'name']] = df_interv['Interventions'].str.split(':', n=1, expand=True)

# Stripping whitespace
df_interv['intervention_type'] = df_interv['intervention_type'].str.strip()
df_interv['name'] = df_interv['name'].str.strip()

# Selecting final Interventions table
df_interventions = df_interv[['study_id', 'intervention_type', 'name']]

# Original dataset does not have a 'description' column
# It will be created as a placeholder
df_interventions['description'] = 'Not Specified'

df_interventions.head(10)

,study_id,intervention_type,name,description
0,1,Diagnostic Test,ID Now™ COVID-19 Screening Test,Not Specified
1,2,Drug,Drug COVID19-0001-USR,Not Specified
1,2,Drug,normal saline,Not Specified
2,3,Other,Lung CT scan analysis in COVID-19 patients,Not Specified
3,4,Diagnostic Test,COVID 19 Diagnostic Test,Not Specified
4,5,Diagnostic Test,"Diagnosis of SARS-Cov2 by RT-PCR and : IgG, Ig...",Not Specified
5,6,Biological,Convalescent COVID 19 Plasma,Not Specified
6,7,Behavioral,COVID-19 Breastfeeding Support,Not Specified
8,9,Diagnostic Test,Breath biopsy sampling using the ReCIVA Breath...,Not Specified
9,10,Biological,Convalescent Plasma from COVID-19 donors,Not Specified

In [ ]:
# Exporting
df_interventions.to_csv(os.path.join(export_path, 'interventions_tb.csv'), index=False)

 ---

In [ ]:
# Selecting columns for the study_design table
df_design = df[['Rank', 'Study Designs']].copy()

# Renaming columns to match the database schema
df_design = df_design.rename(columns={
    'Rank':'study_id'
})

# Exploding the 'Study Designs' column to create a new row for each design
df_design['Study Designs'] = df_design['Study Designs'].str.split('|')
df_design = df_design.explode('Study Designs')

# Checking for missing values in date columns
df_design[['Study Designs']].isna().sum()

Study Designs    35
dtype: int64

In [ ]:
# Removing empty rows
df_design = df_design.dropna(subset=['Study Designs'])

In [ ]:
# Function to extract specific values from the 'Study Designs' string
def extract_design_attribute(text, attribute):
    '''
    Extracts specific attributes from a concatenated string.
    
    The 'Study Designs' column in the raw dataset contains multiple key-value pairs separated by pipes (|). 
    This function parses the string, identifies the requested attribute (e.g., 'Masking:', 'Allocation:'), and returns the corresponding clean value.
    
    Parameters:
    text (str): The raw string from the 'Study Designs' column.
    attribute (str): The label to search for within the string.
    
    Returns:
    str: The extracted attribute value, or None if the attribute is not found or the input text is null.
    '''
    if pd.isna(text):
        return None
    # Split the string by the pipe '|' character
    parts = text.split('|')
    for part in parts:
        if attribute in part:
            # Remove the label and return the clean value
            return part.replace(attribute, '').strip()
    return None

# Applying the extraction to create 4 new clean columns
df_design['allocation'] = df_design['Study Designs'].apply(lambda x: extract_design_attribute(x, 'Allocation:'))
df_design['intervention_model'] = df_design['Study Designs'].apply(lambda x: extract_design_attribute(x, 'Intervention Model:'))
df_design['observational_model'] = df_design['Study Designs'].apply(lambda x: extract_design_attribute(x, 'Observational Model:'))
df_design['time_perspective'] = df_design['Study Designs'].apply(lambda x: extract_design_attribute(x, 'Time Perspective:'))
df_design['masking'] = df_design['Study Designs'].apply(lambda x: extract_design_attribute(x, 'Masking:'))
df_design['primary_purpose'] = df_design['Study Designs'].apply(lambda x: extract_design_attribute(x, 'Primary Purpose:'))

In [ ]:
# Dropping the original 'Study Designs' 
df_design = df_design.drop(columns='Study Designs', errors='ignore')

# Check the new columns
df_design.head(20)

,study_id,allocation,intervention_model,observational_model,time_perspective,masking,primary_purpose
0,1,N/A,NaN,NaN,NaN,NaN,NaN
0,1,NaN,Single Group Assignment,NaN,NaN,NaN,NaN
0,1,NaN,NaN,NaN,NaN,None (Open Label),NaN
0,1,NaN,NaN,NaN,NaN,NaN,Diagnostic
1,2,Randomized,NaN,NaN,NaN,NaN,NaN
1,2,NaN,Parallel Assignment,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,"Triple (Participant, Care Provider, Investigator)",NaN
1,2,NaN,NaN,NaN,NaN,NaN,Treatment
2,3,NaN,NaN,Cohort,NaN,NaN,NaN
2,3,NaN,NaN,NaN,Retrospective,NaN,NaN
3,4,NaN,NaN,Cohort,NaN,NaN,NaN
3,4,NaN,NaN,NaN,Retrospective,NaN,NaN
4,5,NaN,NaN,Cohort,NaN,NaN,NaN
4,5,NaN,NaN,NaN,Prospective,NaN,NaN
5,6,N/A,NaN,NaN,NaN,NaN,NaN
5,6,NaN,Single Group Assignment,NaN,NaN,NaN,NaN
5,6,NaN,NaN,NaN,NaN,None (Open Label),NaN
5,6,NaN,NaN,NaN,NaN,NaN,Treatment
6,7,N/A,NaN,NaN,NaN,NaN,NaN
6,7,NaN,Single Group Assignment,NaN,NaN,NaN,NaN

In [ ]:

# Exporting 
df_design.to_csv(os.path.join(export_path, 'study_design_tb.csv'), index=False)

 ---

In [ ]:
df[['Rank', 'Funded Bys']]

      Rank      Funded Bys
0        1           Other
1        2           Other
2        3           Other
3        4        Industry
4        5           Other
...    ...             ...
5778  5779       Other|NIH
5779  5780           Other
5780  5781           Other
5781  5782           Other
5782  5783  Other|U.S. Fed

[5783 rows x 2 columns]

In [ ]:
# Selecting columns for the sponsors table
df_sponsors_raw = df[['Rank', 'Sponsor/Collaborators', 'Funded Bys']].copy()

# Renaming columns to match the database schema
df_sponsors_raw = df_sponsors_raw.rename(columns={'Funded Bys': 'agency_class', 'Rank':'study_id'})

# Function to separate agencies and define who is Lead or Collaborator
# The first agency in the list is considered the Lead, and the others are Collaborators
def process_sponsors(row):
    '''
    This function takes a row of the dataframe, separates the sponsors/collaborators and their classes,
    and returns a list of dictionaries with the agency name, class, and role (Lead or Collaborator).
    '''
    
    agencies = str(row['Sponsor/Collaborators']).split('|')
    classes = str(row['agency_class']).split('|')
    
    results = []
        
    for i, name in enumerate(agencies):
        # The first in the list (index 0) is the Lead, the others are Collaborator
        role = 'Lead' if i == 0 else 'Collaborator'
        
        # Find the corresponding class (if it exists in the same order)
        # If no class is found for all, mark as 'Other' or 'Unknown'
        current_class = classes[i].strip() if i < len(classes) else "Other"
        
        results.append({
            'agency': name.strip(),
            'agency_class': current_class,
            'lead_or_collaborator': role
        })
    return results

# Creating a temporary column with the list of dictionaries
df_sponsors_raw['temp_list'] = df_sponsors_raw.apply(process_sponsors, axis=1)

# Separating the list of dictionaries into individual rows
df_sponsors_final = df_sponsors_raw.explode('temp_list')

# Converting the list of dictionaries into separate columns and cleaning the dataframe
df_sponsors_final = pd.concat([
    df_sponsors_final[['study_id']], 
    df_sponsors_final['temp_list'].apply(pd.Series)
], axis=1)

# Final cleaning
df_sponsors_final = df_sponsors_final[df_sponsors_final['agency'] != 'nan']
df_sponsors_final = df_sponsors_final.dropna(subset=['agency'])

In [ ]:
# Checking the final structure
df_sponsors_final.head(10)

,study_id,agency,agency_class,lead_or_collaborator
0,1,Groupe Hospitalier Paris Saint Joseph,Other,Lead
1,2,United Medical Specialties,Other,Lead
2,3,University of Milano Bicocca,Other,Lead
3,4,Hong Kong Sanatorium & Hospital,Industry,Lead
4,5,Centre Hospitalier Régional d'Orléans,Other,Lead
4,5,Centre de Biophysique Moléculaire - Pr Chantal...,Other,Collaborator
4,5,Professeur TOUMI Hechmi,Other,Collaborator
5,6,Vinmec Research Institute of Stem Cell and Gen...,Other,Lead
5,6,National Institute of Hygiene and Epidemiology...,Other,Collaborator
5,6,"National Hospital for Tropical Diseases, Hanoi...",Other,Collaborator

In [ ]:
# Exporting
df_sponsors_final.to_csv(os.path.join(export_path, 'sponsors_tb.csv'), index=False)

In [ ]:
# Selecting columns for the conditions table
df_cond = df[['Rank', 'Conditions']].copy()

# Renaming columns to match the database schema
df_cond = df_cond.rename(columns={'Rank': 'study_id'})

# Removing empty rows
df_cond = df_cond.dropna(subset=['Conditions'])

# Separating conditions by '|' and expanding into multiple rows
df_cond['condition_name'] = df_cond['Conditions'].str.split('|')
df_conditions = df_cond.explode('condition_name')

# Cleaning whitespace from condition names
df_conditions['condition_name'] = df_conditions['condition_name'].str.strip()

# Selecting the final columns for the SQL table
df_conditions = df_conditions[['study_id', 'condition_name']]

In [ ]:
df_conditions

      study_id                                 condition_name
0            1                                        Covid19
1            2                           SARS-CoV-2 Infection
2            3                                        covid19
3            4                                          COVID
4            5          Maternal Fetal Infection Transmission
...        ...                                            ...
5781      5782                  Anxiety Disorder of Childhood
5781      5782                            Depressive Symptoms
5781      5782  Behavior Problem of Childhood and Adolescence
5781      5782                         Mental Health Disorder
5782      5783                                   Chronic Pain

[11162 rows x 2 columns]

In [ ]:
# Normalization of condition names using regex patterns
# Converting everything to uppercase and removing extra spaces
df_conditions['condition_name'] = df_conditions['condition_name'].str.upper().str.strip()

# Defining patterns (Regex)
covid_pattern = r'.*COVID.*|.*SARS-COV.*|.*CORONAVIRUS.*|.*CORONA VIRUS INFECTION.*'
ards_pattern = r'.*ARDS.*|.*ACUTE RESPIRATORY DISTRESS SYNDROME.*'
pneumonia_pattern = r'.*PNEUMONIA.*|.*PNEUMONIA, VIRAL.*|.*PNEUMONIA, BACTERIAL.*|.*PNEUMONIA, FUNGAL.*|.*SARS PNEUMONIA.*'
sars_pattern = r'.*SARS.*|.*SEVERE ACUTE RESPIRATORY SYNDROME.*'
viral_infection_pattern = r'.*VIRAL INFECTION.*|.*VIRAL INFECTIONS.*|.*VIRAL DISEASE.*|.*VIRUS DISEASES.*|.*INFECTION VIRAL.*'
respiratory_failure_pattern = r'.*RESPIRATORY FAILURE.*|.*RESPIRATORY INSUFFICIENCY.*|.*RESPIRATORY DISTRESS.*'
stress_pattern = r'.*STRESS.*|.*STRESS, PHYSICAL.*|.*STRESS, PSYCHOLOGICAL.*|.*STRESS, EMOTIONAL.*|.*POST TRAUMATIC STRESS DISORDER.*'


# Applying the patterns to normalize condition names
# Merge variations of COVID
df_conditions.loc[df_conditions['condition_name'].str.contains(covid_pattern, na=False), 'condition_name'] = 'COVID-19'

# Merge variations of ARDS
df_conditions.loc[df_conditions['condition_name'].str.contains(ards_pattern, na=False), 'condition_name'] = 'ARDS'

# Merge variations of Pneumonia
df_conditions.loc[df_conditions['condition_name'].str.contains(pneumonia_pattern, na=False), 'condition_name'] = 'PNEUMONIA'

# Merge variations of SARS
df_conditions.loc[df_conditions['condition_name'].str.contains(sars_pattern, na=False), 'condition_name'] = 'SARS'

# Merge variations of Viral Infection
df_conditions.loc[df_conditions['condition_name'].str.contains(viral_infection_pattern, na=False), 'condition_name'] = 'VIRAL INFECTION'

# Merge variations of Respiratory Failure
df_conditions.loc[df_conditions['condition_name'].str.contains(respiratory_failure_pattern, na=False), 'condition_name'] = 'RESPIRATORY FAILURE'

# Merge variations of Stress
df_conditions.loc[df_conditions['condition_name'].str.contains(stress_pattern, na=False), 'condition_name'] = 'STRESS'

df_conditions['condition_name'].value_counts().head(30)

condition_name
COVID-19                        5452
PNEUMONIA                        234
ARDS                             227
STRESS                           198
RESPIRATORY FAILURE              132
SARS                             106
ANXIETY                          100
DEPRESSION                        85
VIRAL INFECTION                   64
CANCER                            60
CRITICAL ILLNESS                  43
QUALITY OF LIFE                   37
HEALTHY                           34
CARDIOVASCULAR DISEASES           33
ACUTE KIDNEY INJURY               25
OBESITY                           25
CYTOKINE STORM                    25
PREGNANCY RELATED                 23
HYPERTENSION                      22
RHEUMATOID ARTHRITIS              22
MULTIPLE SCLEROSIS                19
HEART FAILURE                     19
MENTAL HEALTH WELLNESS 1          19
ANOSMIA                           19
DIABETES                          18
RESPIRATORY TRACT INFECTIONS      18
SURGERY                           17
DIABETES MELLITUS                 17
RESPIRATORY DISEASE               16
STROKE                            15
Name: count, dtype: int64

In [ ]:
# Original dataset does not have 'mesh_term' column
# It will be created as a placeholder
df_conditions['mesh_term'] = 'Not Specified'

In [ ]:
df_conditions.head(10)

   study_id                         condition_name      mesh_term
0         1                               COVID-19  Not Specified
1         2                               COVID-19  Not Specified
2         3                               COVID-19  Not Specified
3         4                               COVID-19  Not Specified
4         5  MATERNAL FETAL INFECTION TRANSMISSION  Not Specified
4         5                               COVID-19  Not Specified
4         5                               COVID-19  Not Specified
5         6                               COVID-19  Not Specified
6         7                               COVID-19  Not Specified
6         7                EXCLUSIVE BREASTFEEDING  Not Specified

In [ ]:
# Exporting
df_conditions.to_csv(os.path.join(export_path, 'conditions_tb.csv'), index=False)

 ---

In [ ]:
# Selecting columns for the outcome measures table
df_outcome = df[['Rank', 'Outcome Measures']].copy()

# Renaming columns to match the database schema
df_outcome = df_outcome.rename(columns={'Rank': 'study_id'})

# Checking for missing values in the 'Outcome Measures' column
df_outcome['Outcome Measures'].isna().sum()

np.int64(35)

In [ ]:

# Removing empty rows
df_outcome = df_outcome.dropna(subset=['Outcome Measures'])

In [ ]:
# Separating outcome measures by '|' and expanding into multiple rows
df_outcome['Outcome Measures'] = df_outcome['Outcome Measures'].str.split('|')
df_outcome = df_outcome.explode('Outcome Measures')

# Cleaning whitespace from outcome measures and dropping the original column
df_outcome['outcome_measure_clean'] = df_outcome['Outcome Measures'].str.strip()
df_outcome.drop(columns=['Outcome Measures'], inplace=True)

In [ ]:
# Function to split the outcome measure into type, measure, time frame, and description
def split_outcome_logic_v2(text):
    '''Splits the outcome measure text into structured components: outcome type, measure, time frame, and description.'''
    if pd.isna(text):
        return "Not Specified", None, "Not Specified", "No description provided"
    
    # Using a comprehensive regex to capture all time patterns
    time_pattern = r'((?:at|after|from|within|and)\s+(?:\d+[\s-]*months?|\d+[\s-]*weeks?|\d+[\s-]*days?|\d+[\s-]*years?|birth|baseline))|(\d+[\s-]*months?|\d+[\s-]*weeks?|\d+[\s-]*days?|\d+[\s-]*years?)'
    
    # Find all time references
    matches = re.findall(time_pattern, text, re.IGNORECASE)
    # cleaning the matches to get a list of time frames
    time_list = [max(m) for m in matches if any(m)] 
    
    time_frame = ", ".join(time_list) if time_list else "Not Specified"
    
    # Separating the measure from the time frame by removing the time references from the original text
    measure = text
    for t in time_list:
        measure = measure.replace(t, "")
    
    # Stripping extra spaces and punctuation from the measure
    measure = measure.strip(" ,.;")
    
    # Since the text is very free-form, the original text was set as the measure and the description pointed to it
    description = "Detailed in measure" if len(measure) > 0 else "No description provided"
    
    return "Not Specified", measure, time_frame, description # there is no clear way to determine the outcome type from the text, so it will be returned as "Not Specified"

# Applying the function to split the outcome measures into structured components
df_outcome[['outcome_type', 'measure', 'time_frame', 'description']] = df_outcome['outcome_measure_clean'].apply(
    lambda x: pd.Series(split_outcome_logic_v2(x))
)

In [ ]:
# Normalization of the 'measure' column to reduce duplicates and improve analysis
# Converting to lowercase to standardize the text
df_outcome['measure'] = df_outcome['measure'].str.lower()

# Removing special characters that could cause duplicates (e.g., hyphens, multiple spaces)
df_outcome['measure'] = df_outcome['measure'].str.replace('-', ' ', regex=False)
df_outcome['measure'] = df_outcome['measure'].str.replace(r'\s+', ' ', regex=True).str.strip()

# Dropping duplicates based on the normalized 'measure' 
# Rows are considered duplicates if the study_id, measure and time_frame are the same
df_outcome = df_outcome.drop_duplicates(subset=['study_id', 'measure', 'time_frame'])

# Capitalizing the first letter of each measure
df_outcome['measure'] = df_outcome['measure'].str.capitalize()

In [ ]:
# Verifying the number of duplicates 
outcome_duplicates = df_outcome.duplicated(subset=['study_id', 'measure', 'time_frame']).sum()

print(f"There are {outcome_duplicates} duplicates in the outcome measures.")

There are 0 duplicates in the outcome measures.

In [ ]:
# Normalization of the 'time_frame' column to have identical time frames represented in the same way
# Initial standardization: Convert to lowercase, replace hyphens with spaces, and ensure a space between numbers and units (e.g., "6months" to "6 months")
df_outcome['time_frame'] = (df_outcome['time_frame']
                            .str.lower()
                            .str.replace('-', ' ', regex=False)
                            .str.replace(r'(\d+)([a-z])', r'\1 \2', regex=True))

# Removing the word "at" from time frames, (except when it is followed by "birth" or "baseline")
df_outcome['time_frame'] = df_outcome['time_frame'].str.replace(r'\b(at|within)\s+(?!birth|baseline)', '', regex=True)

# Converting plural time units to singular
df_outcome['time_frame'] = df_outcome['time_frame'].str.replace(r'\b(days|weeks|months|years)\b', lambda m: m.group(1)[:-1], regex=True)

# Aplying pluralization except when the number is 1
def pluralize(match):
    num = match.group(1)
    unit = match.group(2)
    if num == "1":
        return f"{num} {unit}"
    else:
        return f"{num} {unit}s"

df_outcome['time_frame'] = df_outcome['time_frame'].str.replace(r'\b(\d+)\s+(day|week|month|year)\b', pluralize, regex=True)

# Final cleaning and capitalization
df_outcome['time_frame'] = df_outcome['time_frame'].str.replace(r'\s+', ' ', regex=True).str.strip().str.capitalize()

In [ ]:
df_outcome.head(10)

,study_id,outcome_measure_clean,outcome_type,measure,time_frame,description
0,1,Evaluate the diagnostic performance of the ID ...,Not Specified,Evaluate the diagnostic performance of the id ...,Not specified,Detailed in measure
1,2,Change on viral load results from baseline aft...,Not Specified,Change on viral load results after using covid...,From baseline,Detailed in measure
2,3,A qualitative analysis of parenchymal lung dam...,Not Specified,A qualitative analysis of parenchymal lung dam...,Not specified,Detailed in measure
2,3,A quantitative analysis of parenchymal lung da...,Not Specified,A quantitative analysis of parenchymal lung da...,Not specified,Detailed in measure
2,3,The potential impact of parenchymal morphologi...,Not Specified,The potential impact of parenchymal morphologi...,Not specified,Detailed in measure
2,3,Automated segmentation of lung scans of patien...,Not Specified,Automated segmentation of lung scans of patien...,Not specified,Detailed in measure
2,3,Knowledge of chest CT features in COVID-19 pat...,Not Specified,Knowledge of chest ct features in covid 19 pat...,Not specified,Detailed in measure
2,3,The ability within which the analysis of artif...,Not Specified,The ability within which the analysis of artif...,Not specified,Detailed in measure
3,4,Proportion of asymptomatic subjects,Not Specified,Proportion of asymptomatic subjects,Not specified,Detailed in measure
3,4,Proportion of subjects with recent contact his...,Not Specified,Proportion of subjects with recent contact his...,Not specified,Detailed in measure

In [ ]:
# Dropping the temporary 'outcome_measure_clean' column
df_outcome = df_outcome.drop(columns=['outcome_measure_clean'], errors='ignore')

# Exporting
df_outcome.to_csv(os.path.join(export_path, 'outcome_tb.csv'), index=False)