## Preparing for loading

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
# Load the dataset
path = os.path.join('..', 'src', 'Data', 'processed', 'DF_COVID_CLEAN.csv')
df = pd.read_csv(path)

df.head()

,NCT Number,Title,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,Gender,Age,...,allocation,intervention_model,observational_model,time_perspective,masking,primary_purpose,country,Start_Month,Start Year,Completion YearMonth
0,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,"Active, not recruiting",No Results Available,Covid19,Diagnostic Test: ID Now™ COVID-19 Screening Test,Evaluate the diagnostic performance of the ID ...,Groupe Hospitalier Paris Saint Joseph,All,"18 Years and older (Adult, Older Adult)",...,NaN,Single Group Assignment,NaN,NaN,None (Open Label),Diagnostic,France,2020-11,2020,2021-04
1,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,Not yet recruiting,No Results Available,SARS-CoV-2 Infection,Drug: Drug COVID19-0001-USR|Drug: normal saline,Change on viral load results from baseline aft...,United Medical Specialties,All,"18 Years and older (Adult, Older Adult)",...,Randomized,Parallel Assignment,NaN,NaN,"Triple (Participant, Care Provider, Investigator)",Treatment,Colombia,2020-11,2020,2021-01
2,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,Recruiting,No Results Available,covid19,Other: Lung CT scan analysis in COVID-19 patients,A qualitative analysis of parenchymal lung dam...,University of Milano Bicocca,All,"18 Years and older (Adult, Older Adult)",...,NaN,NaN,Cohort,Retrospective,NaN,NaN,Italy,2020-05,2020,2021-06
3,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,"Active, not recruiting",No Results Available,COVID,Diagnostic Test: COVID 19 Diagnostic Test,Proportion of asymptomatic subjects|Proportion...,Hong Kong Sanatorium & Hospital,All,"Child, Adult, Older Adult",...,NaN,NaN,Cohort,Retrospective,NaN,NaN,Hong Kong,2020-05,2020,2020-08
4,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,Recruiting,No Results Available,Maternal Fetal Infection Transmission|COVID-19...,Diagnostic Test: Diagnosis of SARS-Cov2 by RT-...,COVID-19 by positive PCR in cord blood and / o...,Centre Hospitalier Régional d'Orléans|Centre d...,Female,18 Years to 48 Years (Adult),...,NaN,NaN,Cohort,Prospective,NaN,NaN,France,2020-05,2020,2021-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5571,NCT04011644,Mobile Health for Alcohol Use Disorders in Cli...,Recruiting,No Results Available,Alcohol Drinking|Telemedicine,Behavioral: A-CHESS self-monitored|Behavioral:...,Number of risky drinking days|Number of patien...,"University of Wisconsin, Madison|National Inst...",All,"21 Years to 100 Years (Adult, Older Adult)",...,Randomized,Parallel Assignment,NaN,NaN,None (Open Label),Treatment,United States,2020-03,2020,2023-04
5572,NCT04681339,Antibiotic Prescription in Children Hospitaliz...,Not yet recruiting,No Results Available,Community Acquired Pneumonia in Children|Antib...,Other: Antibiotic treatment|Other: No antibiot...,Antibiotic treatment rates in hospitalized chi...,ARCIM Institute Academic Research in Complemen...,All,"3 Months to 18 Years (Child, Adult)",...,NaN,NaN,Cohort,Prospective,NaN,NaN,Germany,2021-04,2021,2024-12
5573,NCT04740229,Moderate-intensity Flow-based Yoga Effects on ...,Recruiting,No Results Available,Stress|Psychological,Behavioral: Yoga,Perceived Stress|Task switching paradigm|Digit...,University of Illinois at Urbana-Champaign,All,18 Years to 64 Years (Adult),...,Randomized,Parallel Assignment,NaN,NaN,"Double (Investigator, Outcomes Assessor)",Treatment,United States,2021-02,2021,2021-07
5574,NCT04804917,3-year Follow-up of the Mind My Mind RCT,Recruiting,No Results Available,Emotional Problem|Anxiety Disorder of Childhoo...,NaN,The child's impact of mental health problems r...,"Mental Health Services in the Capital Region, ...",All,"8 Years to 20 Years (Child, Adult)",...,NaN,NaN,Other,Prospective,NaN,NaN,Denmark,2021-03,2021,2022-12
5575,NCT04680000,Chronic Pain Management In Primary Care Using ...,Not yet recruiting,No Results Available,Chronic Pain,Behavioral: Brief Cognitive Behavioral Therapy...,Defense and Veterans Pain Rating Scale (DVPRS)...,The University of Texas Health Science Center ...,All,"18 Years and older (Adult, Older Adult)",...,Randomized,Parallel Assignment,NaN,NaN,None (Open Label),Treatment,United States,2021-02,2021,2025-02

In [4]:
# Creating a study ID column
df.insert(0, 'study_id', range(1, len(df) + 1))


df.head()

,study_id,NCT Number,Title,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,Gender,...,allocation,intervention_model,observational_model,time_perspective,masking,primary_purpose,country,Start_Month,Start Year,Completion YearMonth
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,"Active, not recruiting",No Results Available,Covid19,Diagnostic Test: ID Now™ COVID-19 Screening Test,Evaluate the diagnostic performance of the ID ...,Groupe Hospitalier Paris Saint Joseph,All,...,NaN,Single Group Assignment,NaN,NaN,None (Open Label),Diagnostic,France,2020-11,2020,2021-04
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,Not yet recruiting,No Results Available,SARS-CoV-2 Infection,Drug: Drug COVID19-0001-USR|Drug: normal saline,Change on viral load results from baseline aft...,United Medical Specialties,All,...,Randomized,Parallel Assignment,NaN,NaN,"Triple (Participant, Care Provider, Investigator)",Treatment,Colombia,2020-11,2020,2021-01
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,Recruiting,No Results Available,covid19,Other: Lung CT scan analysis in COVID-19 patients,A qualitative analysis of parenchymal lung dam...,University of Milano Bicocca,All,...,NaN,NaN,Cohort,Retrospective,NaN,NaN,Italy,2020-05,2020,2021-06
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,"Active, not recruiting",No Results Available,COVID,Diagnostic Test: COVID 19 Diagnostic Test,Proportion of asymptomatic subjects|Proportion...,Hong Kong Sanatorium & Hospital,All,...,NaN,NaN,Cohort,Retrospective,NaN,NaN,Hong Kong,2020-05,2020,2020-08
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,Recruiting,No Results Available,Maternal Fetal Infection Transmission|COVID-19...,Diagnostic Test: Diagnosis of SARS-Cov2 by RT-...,COVID-19 by positive PCR in cord blood and / o...,Centre Hospitalier Régional d'Orléans|Centre d...,Female,...,NaN,NaN,Cohort,Prospective,NaN,NaN,France,2020-05,2020,2021-05

In [5]:
df.columns

Index(['study_id', 'NCT Number', 'Title', 'Status', 'Study Results',
       'Conditions', 'Interventions', 'Outcome Measures',
       'Sponsor/Collaborators', 'Gender', 'Age', 'Phases', 'Enrollment',
       'Funded Bys', 'Study Type', 'Start Date', 'Primary Completion Date',
       'Completion Date', 'allocation', 'intervention_model',
       'observational_model', 'time_perspective', 'masking', 'primary_purpose',
       'country', 'Start_Month', 'Start Year', 'Completion YearMonth'],
      dtype='object')

In [6]:
# Selecting columns for the studies table
cols_studies = ['study_id','NCT Number', 'Title', 'Status', 'Phases', 
    'Study Type', 'Start Date', 'Completion Date', 'Primary Completion Date', 'Enrollment', 'Gender'
]

# Creating the dataframe for studies
df_studies = df[cols_studies].copy()

In [7]:
# Checking Date Formats
df_studies[['Start Date', 'Completion Date']].head()

   Start Date Completion Date
0  2020-11-09      2021-04-30
1  2020-11-02      2021-01-29
2  2020-05-07      2021-06-15
3  2020-05-25      2020-08-31
4  2020-05-05      2021-05-01

In [8]:
# Checking for missing values in date columns
df_studies[['Start Date', 'Completion Date']].isna().sum()

Start Date         0
Completion Date    0
dtype: int64

In [9]:
# Renaming columns to match the database schema
df_studies = df_studies.rename(columns={
    #study_id is already in the correct form
    'NCT Number': 'nct_id',
    'Title': 'title',
    'Status': 'status',
    'Phases': 'phase',
    'Study Type': 'study_type',
    'Start Date': 'start_date',
    'Completion Date': 'completion_date',
    'Primary Completion Date': 'primary_completion_date',
    'Enrollment': 'enrollment',
    'Gender': 'gender'
})

df_studies.head()

,study_id,nct_id,title,status,phase,study_type,start_date,completion_date,primary_completion_date,enrollment,gender
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,"Active, not recruiting",NaN,Interventional,2020-11-09,2021-04-30,2020-12-22,1000,All
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,Not yet recruiting,Phase 1|Phase 2,Interventional,2020-11-02,2021-01-29,2020-12-15,60,All
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,Recruiting,NaN,Observational,2020-05-07,2021-06-15,2021-06-15,500,All
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,"Active, not recruiting",NaN,Observational,2020-05-25,2020-08-31,2020-07-31,2500,All
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,Recruiting,NaN,Observational,2020-05-05,2021-05-01,2021-05-01,50,Female

In [ ]:
# Exporting
export_path = os.path.join('..', 'src', 'data', 'processed', 'structured tables')

df_studies.to_csv(os.path.join(export_path, 'studies.csv'), index=False)

 ---

In [11]:
# Selection of columns for the locations table
df_locations = df[['study_id', 'country']].copy()

# Checking for missing values in date columns
df_locations[['country']].isna().sum()

country    0
dtype: int64

In [ ]:
# Exporting 
df_locations.to_csv(os.path.join(export_path, 'locations.csv'), index=False)

 ---

In [13]:
# Selecting columns for the interventions table
df_interv = df[['study_id', 'Interventions']].copy()

# Separating type from details
df_interv['Interventions'] = df_interv['Interventions'].str.split('|')
df_interv = df_interv.explode('Interventions')

# Checking for missing values in date columns
df_interv[['Interventions']].isna().sum()

Interventions    863
dtype: int64

In [14]:
# Removing empty rows
df_interv = df_interv.dropna(subset=['Interventions'])

# Dividing the 'Interventions' column into 'type' and 'description'
df_interv[['intervention_type', 'description']] = df_interv['Interventions'].str.split(':', n=1, expand=True)

# Stripping whitespace
df_interv['intervention_type'] = df_interv['intervention_type'].str.strip()
df_interv['description'] = df_interv['description'].str.strip()

# Selecting final Interventions table
df_interventions = df_interv[['study_id', 'intervention_type', 'description']] # already in the correct name format

df_interventions

,study_id,intervention_type,description
0,1,Diagnostic Test,ID Now™ COVID-19 Screening Test
1,2,Drug,Drug COVID19-0001-USR
1,2,Drug,normal saline
2,3,Other,Lung CT scan analysis in COVID-19 patients
3,4,Diagnostic Test,COVID 19 Diagnostic Test
...,...,...,...
5572,5573,Other,Antibiotic treatment
5572,5573,Other,No antibiotic treatment
5573,5574,Behavioral,Yoga
5575,5576,Behavioral,Brief Cognitive Behavioral Therapy for Chronic...
5575,5576,Other,BCBT-CP Booster

In [ ]:
# Exporting
df_interventions.to_csv(os.path.join(export_path, 'interventions.csv'), index=False)

 ---

In [16]:
# Selecting columns for the study design table
cols_design = [
    'study_id', 'allocation', 'intervention_model', 
    'observational_model', 'time_perspective', 'masking', 'primary_purpose'
]

df_design = df[cols_design].copy()

# Replacing empty strings and NaN with None
df_design = df_design.replace({pd.NA: None, float('nan'): None})

df_design

,study_id,allocation,intervention_model,observational_model,time_perspective,masking,primary_purpose
0,1,None,Single Group Assignment,None,None,None (Open Label),Diagnostic
1,2,Randomized,Parallel Assignment,None,None,"Triple (Participant, Care Provider, Investigator)",Treatment
2,3,None,None,Cohort,Retrospective,None,None
3,4,None,None,Cohort,Retrospective,None,None
4,5,None,None,Cohort,Prospective,None,None
...,...,...,...,...,...,...,...
5571,5572,Randomized,Parallel Assignment,None,None,None (Open Label),Treatment
5572,5573,None,None,Cohort,Prospective,None,None
5573,5574,Randomized,Parallel Assignment,None,None,"Double (Investigator, Outcomes Assessor)",Treatment
5574,5575,None,None,Other,Prospective,None,None
5575,5576,Randomized,Parallel Assignment,None,None,None (Open Label),Treatment

In [ ]:

# Exporting 
df_design.to_csv(os.path.join(export_path, 'study_design.csv'), index=False)

 ---

In [18]:
# Selecting columns for the sponsors table
df_sponsors_raw = df[['study_id', 'Sponsor/Collaborators', 'Funded Bys']].copy()

# Renaming columns to match the database schema
df_sponsors_raw = df_sponsors_raw.rename(columns={'Funded Bys': 'agency_class'})

# Function to separate agencies and define who is Lead or Collaborator
# The first agency in the list is considered the Lead, and the others are Collaborators
def process_sponsors(row):
    '''
    This function takes a row of the dataframe, separates the sponsors/collaborators and their classes,
    and returns a list of dictionaries with the agency name, class, and role (Lead or Collaborator).
    '''
    
    agencies = str(row['Sponsor/Collaborators']).split('|')
    classes = str(row['agency_class']).split('|')
    
    results = []
        
    for i, name in enumerate(agencies):
        # The first in the list (index 0) is the Lead, the others are Collaborator
        role = 'Lead' if i == 0 else 'Collaborator'
        
        # Find the corresponding class (if it exists in the same order)
        # If no class is found for all, mark as 'Other' or 'Unknown'
        current_class = classes[i].strip() if i < len(classes) else "Other"
        
        results.append({
            'agency': name.strip(),
            'agency_class': current_class,
            'lead_or_collaborator': role
        })
    return results

# Creating a temporary column with the list of dictionaries
df_sponsors_raw['temp_list'] = df_sponsors_raw.apply(process_sponsors, axis=1)

# Separating the list of dictionaries into individual rows
df_sponsors_final = df_sponsors_raw.explode('temp_list')

# Converting the list of dictionaries into separate columns and cleaning the dataframe
df_sponsors_final = pd.concat([
    df_sponsors_final[['study_id']], 
    df_sponsors_final['temp_list'].apply(pd.Series)
], axis=1)

# Final cleaning
df_sponsors_final = df_sponsors_final[df_sponsors_final['agency'] != 'nan']
df_sponsors_final = df_sponsors_final.dropna(subset=['agency'])

df_sponsors_final.head(10)

,study_id,agency,agency_class,lead_or_collaborator
0,1,Groupe Hospitalier Paris Saint Joseph,Other,Lead
1,2,United Medical Specialties,Other,Lead
2,3,University of Milano Bicocca,Other,Lead
3,4,Hong Kong Sanatorium & Hospital,Industry,Lead
4,5,Centre Hospitalier Régional d'Orléans,Other,Lead
4,5,Centre de Biophysique Moléculaire - Pr Chantal...,Other,Collaborator
4,5,Professeur TOUMI Hechmi,Other,Collaborator
5,6,Vinmec Research Institute of Stem Cell and Gen...,Other,Lead
5,6,National Institute of Hygiene and Epidemiology...,Other,Collaborator
5,6,"National Hospital for Tropical Diseases, Hanoi...",Other,Collaborator

In [ ]:
# Exporting
df_sponsors.to_csv(os.path.join(export_path, 'sponsors.csv'), index=False)